//
// Created by ts on 4/24/2019.
//

#ifndef BRICKBREAKER_INPUTACTION_H
#define BRICKBREAKER_INPUTACTION_H

enum InputAction {
    QUIT_PROGRAM, LEFT_ARROW, RIGHT_ARROW, MOUSE_MOVEMENT, MOUSE_CLICK, NOTHING
};

#endif //BRICKBREAKER_INPUTACTION_H
